### ISSUE TITLE
Support for Uppercase letters

### ISSUE THREAD

**Issue by AKlepac** [AKlepac/Symmetric-Encryption#6]
Currently attempting to encrypt a Uppercase character will result in an error as the cypher system does not support it.

**Comment by KierenP** [comment]
Maybe change 

`if (text[x] == cypher[i][y]){`

Into

`if (text[x] == cypher[i][y] || text[x] == cypher[i][y] - 32){`

This way a input of 'a' is matched with the cypher's 'a', but a input of 'A' is also matched with the cypher's 'a' - 32 = 'A'

*See ascii table

Basically treat 'a' and 'A' the same

**Comment by KierenP** [comment]
Possibly solved in e4919eae8c408c6ba8559d366010a97c0f6cad86
